swipe:
  3:
    left:
      command: "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut Switch One Desktop to the Right"
    right:
      command: "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut Switch One Desktop to the Left"
    up:
      command: "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut Switch One Desktop Down"
    down:
      command: "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut"Switch One Desktop Up"
  4:
    left:
      command: ""
    right:
      command: ""
    up:
      command: "qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut ShowDesktopGrid"
    down:
      command: ""
pinch:
  in:
    command: ""
  out:
    command: ""

threshold:
  pinch: 0.5

interval:
  swipe: 0.75
  pinch: 0.5